---
# Note: Do not delete the underscore "_" in the below command, its not a typo, it's to regex an exact match
- name: Check if network object exists
  cisco.asa.asa_command:
    commands: |
      show run object network | grep {{ ansible_hostname }}_
  register: resulty
  when:
    - '"add" in STATE'

- set_fact:
    resultx: "{{ resulty.stdout | map('trim') }}"
  when:
    - '"add" in STATE'

- set_fact:
    hosty: "object network {{ ansible_hostname }}"
  when:
    - '"add" in STATE'
   
- name: "Create network object {{ ansible_hostname }}"
  cisco.asa.asa_command:
    commands: |
      conf t
      object network {{ ansible_hostname }}
      host {{ ip }}
      end
      wr
  when: 
    - '"add" in STATE'
    - 'hosty not in resultx' 
