---
- name: Check if network object exists
  cisco.asa.asa_command:
    commands: |
      show run object network | grep {{ ansible_hostname }}
  register: result
  when:
    - '"add" in STATE'

   
- name: "Create network object {{ ansible_hostname }}"
  cisco.asa.asa_command:
    commands: |
      conf t
      object network {{ ansible_hostname }}
      host {{ ip }}
      end
      wr
  when: 
    - 'result.stdout is defined and ansible_hostname not in result.stdout'
    - '"add" in STATE'
